### ISSUE TITLE
static website .

### ISSUE THREAD

**Issue by stanlygamer** [h-mdm/apuppet-server#10]
I am a student .

I want to create a new project based on this project for my semester .

I can't understand how is this project  works ?

I can't understand what is the puropose of using ubuntu os , docker and so on ?

Is it possible to create a static website for this project ?

Can you expalin in detail ?

**Comment by h-mdm** [comment]
APuppet uses Docker to simplify the installation. Its engine is based on a [Janus](https://janus.conf.meetecho.com/) media server which (currently) doesn't have an installer needs to be compiled and configured to start operating. 

Docker images are working on any Linux. However the Docker itself and some other tools (like Python) needs to be installed as well. So the aPuppet installer is optimized for Ubuntu Linux (and also works on Debian, CentOS, and some other Linux distros). The installer is based on [Ansible](https://www.ansible.com/).

You can read more about the tools used in aPuppet on a related web resources. Also, [this article](https://apuppet.org/technology/) on the aPuppet website could help you understand better the underlying technologies.
