### ISSUE TITLE
Janus only option

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#12]
hi Mr @h-mdm 
could you give me more information about this option which you mentioned in readme file?

best regards

**Comment by FJEagle** [comment]
> 
> 
> hi Mr @h-mdm could you give me more information about this option which you mentioned in readme file?
> 
> best regards

The apuppet-server consists of two components:  Janus and  nginx (certbo + web-admin included).

So, if you want to handle nginx part (ssl cert, web frontend resources, etc.) by yourself, you can specifiy the janus only option.
Then the install.sh won't process nginx part for you.
