### ISSUE TITLE
erverythings work but there is no nginx installed

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#13]
hi Mr @h-mdm 
I need to change nginx settings but I cant find it
among to the installation  it installed by ansible and I saw that every time
but there is only nginx.conf file in nginx folder!!!
its so confuing....
do u have any idea???

**Comment by FJEagle** [comment]
Try to modify deploy/templates/nginx/nginx.conf.j2?

**Comment by h-mdm** [comment]
The template for nginx.conf is located in deploy/templates/nginx/nginx.conf.j2

Sometimes nginx is not started after running install.sh. In this case, you can review logs:

    docker-compose logs nginx

Sometimes when you run ./install.sh again, the service starts normally.
