### ISSUE TITLE
janus backend issue

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#14]
hi Mr @h-mdm 
you said to me that there is no backend part in apuppet server but in "connecting" phase of android,androis app connect to janis server and create and join room ! in this section:

`            @Override
            protected Integer doInBackground(Void... voids) {
                int result = janusTextRoomPlugin.createRoom(sessionId, password);
                if (result != Const.SUCCESS) {
                    return result;
                }

                result = janusTextRoomPlugin.joinRoom("device:" + username, username);
                if (result != Const.SUCCESS) {
                    return result;
                }

                // Streaming
                janusStreamingPlugin = new JanusStreamingPlugin();
                janusStreamingPlugin.init(context);
                result = janusSession.attachPlugin(janusStreamingPlugin);
                if (result != Const.SUCCESS) {
                    return result;
                }

                result = janusStreamingPlugin.create(sessionId, password, isAudio());

                return result;
            }`

so actually there is a backend section which create a room and join android client to that room!
am I write?
and if yes which js file has backend role?

best regards

**Comment by h-mdm** [comment]
This backend is provided by Janus itself, not by aPuppet JS code.

In nginx.conf (deploy/dist/conf/nginx/nginx.conf), you can see this section:

        # Janus REST API
        location ^~ /janus {
            proxy_pass http://127.0.0.1:8088/janus;
#            proxy_http_version 1.1;
#            proxy_set_header Upgrade $http_upgrade;
#            proxy_set_header Connection "upgrade";
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_redirect off;
        }

So the Janus service is just proxied by nginx.

Here is the reference for Janus REST API: https://janus.conf.meetecho.com/docs/rest.html
