### ISSUE TITLE
Error connecting to any provide janus

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#21]
hi Mr @h-mdm 
how is everything?
ok...back to the issue...
when I set  : 
is_nginx_enabled: false
and  install Nginx myself ,this error would be shown:

![WhatsApp Image 2021-11-10 at 9 56 16 AM](https://user-images.githubusercontent.com/49278298/141061386-504a45eb-90d2-4ee5-8922-8eaafbde56ec.jpeg)

this is my Nginx conf file:
 
[nginx.conf.txt](https://github.com/h-mdm/apuppet-server/files/7511878/nginx.conf.txt)

I had to change the SSL files address to:

        ssl_certificate     /root/apuppet-server/deploy/dist/ssl/live/abc.com/fullchain.pem;
        ssl_certificate_key /root/apuppet-server/deploy/dist/ssl/live/abc.com/privkey.pem;

I don't know how but there is no "/etc/letsencrypt/live/" location after all
also I change this part:

   
        location ^~ /web-admin/ {
            alias /var/www/web-admin/html/;
            index index.html;
        }

to

  
        location ^~ /web-admin/ {
            alias /root/apuppet-server/deploy/dist/web-admin/;
            index index.html;
        }

any help will be appreciated.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
as always thanks a lot for your very very quick response
1. the firewall is inactive
2. port:8089 is close. that means Janus is down
 
I was wondering how could I check Janus's status or force it up running!!
with "is_nginx_enabled: true" everything is ok!
the problem comes out when I set "is_nginx_enabled: false"!!

again any help will be appreciated
best regards,
peiman sh.

**Comment by h-mdm** [comment]
You can check logs to diagnose the issue. You need to cd to the aPuppet directory and run the command:

docker-compose logs janus

The logs may help to determine why Janus is not starting.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
thanks a a lot for your kindness
I did it for a day and I get this error again;n again:

janus_1  | Checking command line arguments...
janus_1  | [janus.jcfg]
janus_1  |     general: {
janus_1  |         configs_folder: /usr/local/etc/janus
janus_1  |         plugins_folder: /usr/local/lib/janus/plugins
janus_1  |         transports_folder: /usr/local/lib/janus/transports
janus_1  |         events_folder: /usr/local/lib/janus/events
janus_1  |         loggers_folder: /usr/local/lib/janus/loggers
janus_1  |         debug_level: 5
janus_1  |         debug_timestamps: true
janus_1  |         debug_colors: true
janus_1  |         api_secret: E9TPQ74Q
janus_1  |         admin_secret: eyUu5m56jG4MNU2
janus_1  |         protected_folders: [
janus_1  |             /bin
janus_1  |             /boot
janus_1  |             /dev
janus_1  |             /etc
janus_1  |             /initrd
janus_1  |             /lib
janus_1  |             /lib32
janus_1  |             /lib64
janus_1  |             /proc
janus_1  |             /sbin
janus_1  |             /sys
janus_1  |             /usr
janus_1  |             /var
janus_1  |             /usr/local/bin
janus_1  |             /usr/local/etc
janus_1  |             /usr/local/include
janus_1  |             /usr/local/lib
janus_1  |             /usr/local/lib32
janus_1  |             /usr/local/lib64
janus_1  |             /usr/local/sbin
janus_1  |         ]
janus_1  |     }
janus_1  |     certificates: {
janus_1  |         cert_pem: /etc/letsencrypt/live/topdesk.ir/fullchain.pem
janus_1  |         cert_key: /etc/letsencrypt/live/topdesk.ir/privkey.pem
janus_1  |         dtls_accept_selfsigned: true
janus_1  |     }
janus_1  |     media: {
janus_1  |         rtp_port_range: 10000-10500
janus_1  |     }
janus_1  |     nat: {
janus_1  |         nice_debug: false
janus_1  |         ice_ignore_list: vmnet
janus_1  |     }
janus_1  |     plugins: {
janus_1  |     }
janus_1  |     transports: {
janus_1  |     }
janus_1  |     loggers: {
janus_1  |     }
janus_1  |     events: {
janus_1  |     }
janus_1  | Debug/log level is 5
janus_1  | Debug/log timestamps are enabled
janus_1  | Debug/log colors are enabled
janus_1  | [Thu Nov 11 16:37:10 2021] Adding 'vmnet' to the ICE ignore list...
janus_1  | [Thu Nov 11 16:37:10 2021] Selecting local IP address...
janus_1  | [Thu Nov 11 16:37:10 2021] Using 193.105.234.198 as local IP...
janus_1  | [Thu Nov 11 16:37:10 2021] [WARN] Token based authentication disabled
janus_1  | [Thu Nov 11 16:37:10 2021] Initializing recorder code
janus_1  | [Thu Nov 11 16:37:10 2021] RTP port range: 10000 -- 10500
janus_1  | [Thu Nov 11 16:37:10 2021] Initializing ICE stuff (Full mode, ICE-TCP                                                                                                                                                              candidates disabled, half-trickle, IPv6 support disabled)
janus_1  | [Thu Nov 11 16:37:10 2021] ICE port range: 10000-10500
janus_1  | [Thu Nov 11 16:37:10 2021] TURN REST API backend: (disabled)
janus_1  | [Thu Nov 11 16:37:10 2021] Using certificates:
janus_1  |      /etc/letsencrypt/live/topdesk.ir/fullchain.pem
janus_1  |      /etc/letsencrypt/live/topdesk.ir/privkey.pem
janus_1  | [Thu Nov 11 16:37:10 2021] Crypto: BoringSSL
janus_1  | [Thu Nov 11 16:37:10 2021] [FATAL] [dtls.c:janus_dtls_load_keys:331]                                                                                                                                                              Error opening certificate file
janus_1  | Janus commit: 04229be3eeceb28dbc57a70a57928aab223895a5
janus_1  | Compiled on:  Sun Nov  8 11:48:45 UTC 2020
janus_1  |
janus_1  | Logger plugins folder: /usr/local/lib/janus/loggers
janus_1  | [WARN]       Couldn't access logger plugins folder...
janus_1  | ---------------------------------------------------
janus_1  |   Starting Meetecho Janus (WebRTC Server) v0.10.7
janus_1  | ---------------------------------------------------

**Comment by h-mdm** [comment]
janus_1 | [Thu Nov 11 16:37:10 2021] [FATAL] [dtls.c:janus_dtls_load_keys:331] Error opening certificate file

Looks like Janus can't open the certificate file so it can't start.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
again thanks a lot for your quick response 
but the nginx uses those key with no problem
![topdesk](https://user-images.githubusercontent.com/49278298/141435566-11d19779-fc8b-448d-900a-74b62bbdba99.png)

is it related to nginx.conf ?
I simplified nginx.conf to :

worker_processes 1;
user root;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        listen              443 ssl;
        server_name .topdesk.ir;
        ssl_certificate     /etc/letsencrypt/live/topdesk.ir/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/topdesk.ir/privkey.key;
        ssl_password_file   /etc/letsencrypt/live/topdesk.ir/global.pass;
        include /etc/nginx/mime.types;

        # Web Admin
        location ^~ /web-admin/ {
            alias /root/apuppet-server/deploy/dist/web-admin/;
            index index.html;
        }

        # static files will be served directly and cached
        location ~* ^.+\.(?:css|cur|js|jpe?g|gif|ico|png|otf|ttf|eot|woff|woff2|svg)$ {
            access_log off;
            expires 3h;
            add_header Cache-Control public;
            tcp_nodelay off;
        }
  
        location ^~ /.well-known/pki-validation/ {
            default_type "text/plain";
            allow all;
            alias /root/apuppet-server/deploy/dist/web-admin/.well-known/pki-validation/;
        }

        location / {
            return 302 $scheme://$host/web-admin/;
        }

        # Janus REST API
        location ^~ /janus {
            proxy_pass http://127.0.0.1:8088/janus;
        }
    }
}



as you saw my SSL files are different from which let'sencrypt generated
I have no cipher but have password
could you give me a clue?

best regard,
peimn sh.

**Comment by h-mdm** [comment]
I think the problem is that your keys are protected by password, whereas LetsEncrypt's keys aren't. Default Janus configs in aPuppet do not have a password.

An easiest solution would be to remove password from your key file.

More complicated solution would be to specify the pass file:
1. Upload the pass file to the Janus docker image (just place it in deploy/dist/ssl/ directory and it will appear in the image in /etc/letsencrypt directory in the image) 
2. Update the parameter cert_pwd in Janus config files (janus.jcfg, janus.transport.http.jcfg, janus.transport.websockets.jcfg). The config file templates are located in deploy/templates/janus/ directory.
3. Run ./install.sh to apply your updates to the config files

**Comment by p3im4n** [comment]
thank Mr @h-mdm 
the problem solved
it was password
sincerely yours ,
peiman sh
