### ISSUE TITLE
Using apache as Proxy - Ubuntu 20.04

### ISSUE THREAD

**Issue by gusarg81** [h-mdm/apuppet-server#22]
Hi, I would like to use my local Apache as proxy to wss websocket. Also, I already have LetsEncrypt configured locally in my server.

config.yaml:

> hostname: "home.ddns.gdnet.ar"
> is_certbot_enabled: false
> is_nginx_enabled: false
> api_http_port: 8188
> api_https_port: 8189
> api_wss: true
> api_wss_port: 8989

Now, how I must configure the wss proxy for apache? Currently I've configured the web-admin folder in my VirtualHost:

> ...
> Alias /apuppet /var/www/virtual/apuppet/web-admin
> <Directory "/var/www/virtual/apuppet/web-admin/">
>         Options FollowSymLinks
>         AllowOverride None
>         Order allow,deny
>         Allow from all
> </Directory>
> ...

But of course, this gives me wss connection error.

Thanks in advance.

**Comment by h-mdm** [comment]
There is a special module for Apache proxying WS/WSS requests (I never used it so I couldn't tell you how to configure): https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html
