### ISSUE TITLE
Errors when trying to access web-admin

### ISSUE THREAD

**Issue by gusarg81** [h-mdm/apuppet-server#23]
OS: Ubuntu 20.04
My config.yaml:

> ---
> hostname: "home.ddns.gdnet.ar"
> email: "gustavo.diaz@gdnet.ar"
> is_certbot_enabled: false
> is_nginx_enabled: true
> web_http_port: 8288
> web_https_port: 8289

Errors on browser:

> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/” because the scheme does not match. web-admin
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/” because the scheme does not match. web-admin
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/” because the scheme does not match. web-admin
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/” because the scheme does not match. web-admin
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/css/deps.min.css” because the scheme does not match. deps.min.css
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/css/deps.min.css” because the scheme does not match. deps.min.css
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/css/app.min.css” because the scheme does not match. app.min.css
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/css/app.min.css” because the scheme does not match. app.min.css
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/deps.min.js” because the scheme does not match. deps.min.js
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/deps.min.js” because the scheme does not match. deps.min.js
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/app.min.js” because the scheme does not match. app.min.js
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/app.min.js” because the scheme does not match. app.min.js
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/settings.js” because the scheme does not match. settings.js
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/dist/js/settings.js” because the scheme does not match. settings.js
> actual Janus servers: 
> Array [ "http://home.ddns.gdnet.ar:8088/janus" ]
> app.min.js:1:81488
> janus debug level: all app.min.js:1:81540
> Initializing library app.min.js:1:77252
> Library initialized: true app.min.js:1:1716
> Multiple servers provided (1), will use the first that works app.min.js:1:1884
> Array [ "http://home.ddns.gdnet.ar:8088/janus" ]
> app.min.js:1:1987
> Server #1: trying REST API to contact Janus (http://home.ddns.gdnet.ar:8088/janus) app.min.js:1:7522
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://home.ddns.gdnet.ar:8088/janus. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://home.ddns.gdnet.ar’).
> 
> Probably a network error, is the server down?: 
> Object { message: "Probably a network error, is the server down?", error: TypeError }
> app.min.js:1:8929
> Error Session error: Error connecting to any of the provided Janus servers: Is the server down? janus_session_error app.min.js:1:62102
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://home.ddns.gdnet.ar:8088/janus. (Reason: CORS request did not succeed).
> 
> Cookie “sessionid” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/static/images/favicon.ico” because the scheme does not match. favicon.ico
> Cookie “csrftoken” will be soon treated as cross-site cookie against “http://home.ddns.gdnet.ar:8288/web-admin/static/images
/favicon.ico” because the scheme does not match.

Any ideas?

**Comment by h-mdm** [comment]
Sorry, I can't accept this as an issue because it is related to the integration with a third party product (Apache). A question about proxying WSS through Apache could be asked on appropriate resources: https://stackoverflow.com or https://serverfault.com, where your question will be exposed to thousands of experienced people.

**Comment by gusarg81** [comment]
I am not using Apache aproxy this time... Don't you see the is_nginx_enabled: true?

**Comment by h-mdm** [comment]
Sorry for the mistake. I think the issue is because you're using plain http. APuppet cannot work through plain HTTP, please use HTTPS instead.

**Comment by gusarg81** [comment]
But using HTTPS requires to enable is_certbot_enabled, right? And like I said in the other issue, I already have locally LetsEncrypt configured in this server.

**Comment by h-mdm** [comment]
The parameter is_certbot_enabled initiates the generation of certificates, so your domain becomes available by HTTPS. It does not affect aPuppet's web pages. You need to find why your logs contain plain HTTP URLs and fix the bug (replace http:// by https://).

**Comment by gusarg81** [comment]
Ok, I think I am not making myself clear.

In my server, I already have LetsEncrypt that handles the server domain, which is, home.ddns.gdnet.ar. Now, thats is why in apuppet I setup as is_certbot_enabled: false.

So, having that in mind, how I do enable HTTPS in apuppet by using my local LetsEncrypt cert?

**Comment by h-mdm** [comment]
APuppet stores the certificates and private keys in the following directory:
deploy/dist/ssl/live/your-website/
There are 4 files: chain.pem (certificate chain without the domain certificate), fullchain.pem (certificate chain including the domain certificate), privkey.pem (private key) and cert.pem (domain certificate).
Two files are required and used by aPuppet: fullchain.pem, privkey.pem
So, in your case, I would set is_certbot_enabled: false, and copy files fullchain.pem and privkey.pem to this directory.

**Comment by gusarg81** [comment]
And after copying the certs files, I run install.sh script again?

**Comment by h-mdm** [comment]
Yes, this will load certs to docker images.

**Comment by gusarg81** [comment]
I did this, but does not enable https (web_https_port: 8289).
