### ISSUE TITLE
no touch issue

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#3]

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
finally with your help I succeed to run server
every thing is ok but touch !!
I just watch android machine and no clicking is affected to android

best regards

**Comment by h-mdm** [comment]
I'm happy that you succeeded to run the aPuppet server!

I guess there could be an ICE negotiation error: https://qa.h-mdm.com/9537/  but need more details for diagnostics.

May I ask you to send your server URL and secret to the aPuppet feedback URL: https://apuppet.org/contact-us/ 

Also run the following command on your server:

ifconfig

and send the result of this command (this will show whether your server is behind the NAT).

**Comment by p3im4n** [comment]
root@SzMgW1cV:~# ifconfig
br-55d63c9b95af: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.21.0.1  netmask 255.255.0.0  broadcast 172.21.255.255
        inet6 fe80::42:85ff:fe07:b08e  prefixlen 64  scopeid 0x20<link>
        ether 02:42:85:07:b0:8e  txqueuelen 0  (Ethernet)
        RX packets 99  bytes 8539 (8.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 83  bytes 16740 (16.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:b7ff:fe4a:a5f3  prefixlen 64  scopeid 0x20<link>
        ether 02:42:b7:4a:a5:f3  txqueuelen 0  (Ethernet)
        RX packets 1907  bytes 106998 (106.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1915  bytes 3308487 (3.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 103.215.221.222  netmask 255.255.255.192  broadcast 103.215.221.255
        inet6 fe80::216:3eff:fe93:3af5  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:93:3a:f5  txqueuelen 1000  (Ethernet)
        RX packets 9726538  bytes 1094419338 (1.0 GB)
        RX errors 97704  dropped 0  overruns 0  frame 97704
        TX packets 643220  bytes 347048702 (347.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 18879  bytes 1960031 (1.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18879  bytes 1960031 (1.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethacdbc36: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::60f0:dff:fe40:ccaa  prefixlen 64  scopeid 0x20<link>
        ether 62:f0:0d:40:cc:aa  txqueuelen 0  (Ethernet)
        RX packets 89  bytes 8982 (8.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 223  bytes 25480 (25.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@SzMgW1cV:~#

**Comment by h-mdm** [comment]
Your setup has been reviewed, and I didn't find any issues. Both screen sharing and gestures are working. 

I noticed that your domain is not available in some countries (I had to use VPN to access it!).

Anyway, since your setup has no problems, I'm closing this issue. If you find any other issues, please do not re-open this ticket, create a new one instead.
