### ISSUE TITLE
edit web site

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#4]
hi Mr @h-mdm 
Im going to add some future to the site such a managing panel and accounting ....
could you give me some tips?

best regards

**Comment by h-mdm** [comment]
If you need to modify the source code of the web admin application, modify the web-admin folder and run the following command to apply your changes:

ansible-playbook deploy/pre_webadmin.yaml

See more details in README.md.

Note that aPuppet web panel is a pure HTML/CSS/JS application, it doesn't include any server-side scripts (like PHP). 

If you need to embed a PHP code, interaction with a database, or any other server-side code, I would suggest you to proceed in the following way:

1. Develop a standalone web application (a web portal with managing, accounting etc.) using the technology you know best;
2. As a part of your web portal, develop the REST API for authorization and accounting, and use it in the aPuppet web panel code (call that REST API by JavaScript);
3. Make a link to the aPuppet web panel in your portal.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
futures have changed....
I want to add chat and file transfer to the index.html with java-script
is that possible?
do you have any guide?


best regards

**Comment by h-mdm** [comment]
This software is open source. You can modify whatever you want without any restrictions. To modify the code, I recommend you to fork the original repository, so you will be able to maintain your own branch as well as merge latest changes from the original repository.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
thanks for your fast replies
I have never write a website in your way
with this deploy method its so difficult to see changes every time I made a change!
of course you ,yourself have not did it every time!
what did you do for writing that Masterpiece؟


с уважением

**Comment by p3im4n** [comment]
hi Mr@h-mdm 
you closed my issue and forget to guide me to develop apuppet server
I will be appreciated if you show me the way

best regards

**Comment by h-mdm** [comment]
I am sorry, I would be happy to respond to ISSUES and fix them, but I cannot guide you in custom development.

**Comment by p3im4n** [comment]
I just wanted a clue to find my answers
any way,I found out you use ansible...
finally I will find the solution with or with out help
good-luck Mr @h-mdm
