### ISSUE TITLE
How to deploy this project on internet?

### ISSUE THREAD

**Issue by poorvajappja** [h-mdm/apuppet-server#5]
How to deploy this project on internet?

I asked this question because I didn't know   more about this.

I already host some websites on internet. 

But   , this project is different. 

Can you give a guide for me to deploy this project on internet ?

**Comment by h-mdm** [comment]
Please read the README.md, section "Deployment". 

You need a virtual machine running Ubuntu Linux (with root access), and a domain name linked to this server.

**Comment by p3im4n** [comment]
> Can you give a guide for me to deploy this project on internet ?

feel free to ask any help
peimansh2014@gmail.com
