### ISSUE TITLE
add file transfer to chat

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#8]
hi MR @h-mdm 
Im trying to add file transfer to janus chat
is that possible with data method or what....
do I have to use another plugin?

best regards

**Comment by h-mdm** [comment]
I accept this as a feature request. A very good feature indeed! 

If you prefer to implement it yourself based on the existing version of aPuppet, please be aware that you need to implement file segmentation and reliable packet delivery via UDP (because UDP is packet-based, not stream-based).

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
I  finally added file sharing feature to apuppet server with ftp server and some nodejs backend files
further more I changed chat feature  
I have some question about janus backend section,Im talking about "connect" phase of android which I will ask in another topic
 thanks for your helps
