### ISSUE TITLE
add nodejs backend

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#9]
hi Mr @h-mdm 
I've install npm and nodejs on apuppet-server
these are the facts:

root@SzMgW1cV:~# node -v
v10.19.0
root@SzMgW1cV:~# npm -v
6.14.4
root@SzMgW1cV:~# which node
/usr/bin/node
root@SzMgW1cV:~# which npm
/usr/bin/npm
 
I install basic-ftp too
then add my code to index.html and add app.js file to web-admin folder
then I re deploy apuppet-server
the code is simple and work on another server
but here I think its dont find nodejs module

do you have any idea?

**Comment by h-mdm** [comment]
aPuppet server is working as a docker container. The application running in a container does not have access to the apps installed on a host machine.

You need to install apps in the aPuppet container.

The installation scripts are located in the "deploy" folder. They are Ansible scripts. You can add required packages in the deploy/pre_requisites.yaml, for example, in the section "Install required system packages". However I recommend you to check out the Ansible documentation first: https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
 I did what u said, every things installed by ansible task successfully
but there are some undefine and undeclare errors
these are some picture of server and IE and chrome browser's console:

![npm list](https://user-images.githubusercontent.com/49278298/111769517-903cce80-88be-11eb-9d0f-047f3d991871.PNG)
![playbook](https://user-images.githubusercontent.com/49278298/111769558-9c289080-88be-11eb-88ab-5f7524aa050f.PNG)
![IE](https://user-images.githubusercontent.com/49278298/111769588-a480cb80-88be-11eb-939a-02a3df1d0b99.PNG)
![chrome](https://user-images.githubusercontent.com/49278298/111769643-b498ab00-88be-11eb-92b9-21ef89cc1ccc.PNG)

I've still searching for find the solution

best regards

**Comment by h-mdm** [comment]
I am sorry but this topic is beyond the aPuppet support. We do not provide support for custom development. I recommend you to post your question on stackoverflow.com.

**Comment by h-mdm** [comment]
Sorry but this is not something I can help you with. 

You can check whether the basic-ftp script is among the files included in the webpage. And if it is not, then you need to understand why.

**Comment by p3im4n** [comment]
hi Mr @h-mdm 
I try to install basic-ftp into the web-admin/node_modules folder by these lines:

`  - name: Install required system packages
    apt:
      package:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - npm
      update_cache: No
      state: latest

  - name: Install "basic-ftp" node.js package.
    community.general.npm:
     name: basic-ftp
     path: ../web-admin/node_modules
     state: latest`

 but it cause many errors

 I know you said ;"stop asking me"
but apuppet is your propery and you r  only one know about detailes 
please please please just take one glance at your source and tell me where can I add npm modules to apuppet

best regards

**Comment by h-mdm** [comment]
Sorry, perhaps my explanation was not clear. 

The purpose of this forum is reporting the bugs and issues of aPuppet remote control server. If you have an issue with aPuppet, I would be happy to comment it.

But if you have issues with the custom development, you need to use related programmer forums. 

Your topic is not related to aPuppet. It is a general development question of integration between npm and docker. Therefore, you need to ask this question on https://stackoverflow.com. On that website, you will most probably get a qualified answer to your question. But on this website you will not, because npm is not being used in aPuppet.

**Comment by h-mdm** [comment]
For your information, all JS scripts are currently stored as a static scripts (not dependencies) in web-admin/js (and added to a gulpfile.js which builds a resulting minified web page). 

You can add your scripts similar to existing scripts without using npm and that should work.
